# Generated by Django 5.2 on 2025-04-16 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTodoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_todos', to='app.schedule')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_schedules', to='todo.todo')),
            ],
        ),
    ]
