# Generated by Django 5.2 on 2025-04-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder_todo_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='todoタスクID'),
        ),
    ]
