# Generated by Django 5.2 on 2025-04-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finished_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
