# Generated by Django 5.2 on 2025-04-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_finished_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='finished_Time',
            new_name='expire_Time',
        ),
    ]
