# Generated by Django 5.2 on 2025-04-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_finished_time_todo_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='expire_Time',
            new_name='expire_time',
        ),
    ]
