# Generated by Django 5.2 on 2025-04-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_expire_time_todo_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='expire_date',
            new_name='expire_datetime',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='expire_time',
        ),
    ]
