# Generated by Django 5.2 on 2025-04-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_expire_date_todo_expire_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
