# Generated by Django 5.2 on 2025-04-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletodolink',
            name='created_from',
            field=models.CharField(choices=[('schedule', 'Schedule'), ('todo', 'Todo')], db_index=True, default='schedule', editable=False, help_text='最初に作成された元のアプリ', max_length=10),
        ),
    ]
