# Generated by Django 5.2 on 2025-04-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder_todo_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
