# Generated by Django 5.2 on 2025-04-16 00:09

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='内容')),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='開始時間')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='終了時間')),
                ('date', models.DateField(verbose_name='日付')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='開始日')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='終了日')),
                ('user_id', models.IntegerField(default=1, verbose_name='ユーザーID')),
                ('project_id', models.IntegerField(default=1, verbose_name='プロジェクトID')),
                ('reminder_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='タスクID')),
            ],
        ),
    ]
