# Generated by Django 5.2 on 2025-04-18 00:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了日'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日'),
        ),
    ]
