# Generated by Django 5.2 on 2025-04-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_schedule_end_date_remove_schedule_end_time_and_more'),
        ('app', '0002_schedule_is_completed'),
    ]

    operations = [
    ]
