# Generated by Django 5.2 on 2025-04-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schedule_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='reminder_enabled',
            field=models.BooleanField(default=True, verbose_name='リマインダー有効'),
        ),
    ]
