# Generated by Django 5.2 on 2025-04-21 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20250421_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了日時'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始日時'),
        ),
    ]
